### ISSUE TITLE
Write unit test for `append`

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#359]
Write a unit test to verify that `append` merges `Documents` correctly.  The merge operation should import new triples into the graph and then regenerate the `Document` from the merged triple store.  The process is entirely additive, and it is not possible to delete data this way.  I'm not sure if any kind of merge conflict resolution is necessary for this operation -- my hunch tells me that there isn't.

**Comment by tcmitchell** [comment]
If we regenerate the `Document` from the merged triple store any pointers a program has for objects in the document will be stale. This is problematic, for instance, for `Sequence.compile` when using `IGEM_STANDARD_ASSEMBLY` as the assembly method because `self` ceases to be part of the document after `IGEM_STANDARD_ASSEMBLY` is run. Either a better approach to `append` is needed or `IGEM_STANDARD_ASSEMBLY` needs a different approach. There may be other options as well.
